[tool.poetry]
name = "neo4j-clinical-layer"
version = "0.1.0"
description = "Build a clinical semantic layer to allow an agent to interact with a graph database in consistent and robust way."
authors = [
    "Tomaz Bratanic <tomaz.bratanic@neo4j.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.2"
neo4j = "^5.14.0"
langchain-community = "^0.2.4"
langchain-openai = "^0.1.8"
langchainhub = "^0.1.18"

[tool.langserve]
export_module = "neo4j_clinical_layer"
export_attr = "agent_executor"

[tool.templates-hub]
use-case = "clinical_layer"
author = "Neo4j"
integrations = ["Neo4j", "OpenAI"]
tags = ["search", "graph-database", "function-calling"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
